# Generated by Django 4.2.1 on 2023-05-19 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_kanbanboard_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='board_member',
            field=models.ManyToManyField(blank=True, related_name='board_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
